import Head from 'next/head'
import DD from '../components/assets/DD.svg'
import Header from '../components/Header/Header';
import Footer from '../components/Footer/Footer';
import Card from '../components/card/Card';
import ServiceCard from '../components/card/ServiceCard';
import Body from '../components/Body/Body';
import Body1 from '../components/Body/Body1';
import Body2 from '../components/Body/Body2';

export default function Home() {
  return (
    <div className="mx-auto">
      <Head>
        <title>Ultimo Food</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main>
      <Body Title="Delivering fresh foods to your doorstep." />
      <Card/>
      <Body1 Title="Our Story" />
      <ServiceCard/>
      <Body2 Title="Fast delivery" />
      </main>
      <Footer/>
    </div>
  )
}
